spring:
  datasource:
    username: root
    password: 030609wyd
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yidongshangcheng
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false